#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

restore0Dir

runApplication -s createBlockMesh createBoxTurb -createBlockMesh

runApplication decomposePar

runParallel createBoxTurb

runParallel $(getApplication)

# ------------------------------------------------------------------------------
