#!/bin/bash
cd "${0%/*}" || exit
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions
#------------------------------------------------------------------------------

# dummy file for post-processing with paraview
touch post.foam

# mesh creation
runApplication blockMesh

# set inlet velocity
cp -r 0.org 0
runApplication setExprBoundaryFields

# decompose and run case
runApplication decomposePar
runParallel renumberMesh -overwrite
runParallel $(getApplication)

#------------------------------------------------------------------------------
